# Generated by Django 4.1.4 on 2023-01-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(max_length=4, verbose_name='性別'),
        ),
    ]
