# Generated by Django 4.1.4 on 2023-01-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_userinfo_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='生理性別'),
        ),
    ]
