# Generated by Django 4.1.5 on 2023-01-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_userinfo_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bithday',
            field=models.DateField(verbose_name='生日快樂'),
        ),
    ]
